spring:
  main:
    banner_mode: console

  application:
    name: study-jpa-study01
    version: 1.0.0
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:~/testdb
    username: sa
    password:

logging:
    level:
      org.springframework: WARN
      plalab.jpa.study01: DEBUG

server:
  port: ${port:8000}

